### ISSUE TITLE
Implement the code explainer

### ISSUE THREAD

**Issue by WouterPennings** [looplanguage/loop#5]
When this function is called, it prints a very beginner friendly explenation of the code.
Example 1:
```
explain {
    var f = fn(x) { x + 2 }
}
```
Print:
> Functions ' f ' has a parameter called ' x ', when ' f ' is called the value of ' x ' is being upped by 2 and that value is returned

Example 2:
```
explain {
    var x = true;
    if ( x ) { x = false; }
}
```
Print:
> A variable called ' x ' is created with the value: ' true '. Then there is an if statement. If the condition of the if statement equals ' true ', ' x ' gets assigned the value of ' false '.

**Comment by kanersps** [comment]
This feature requires first some research into how this can be done in the best way. What words to use in an explanation and how it should be formatted.
