### ISSUE TITLE
Add comments to code

### ISSUE THREAD

**Issue by kanersps** [looplanguage/loop#62]
Currently most of Loop does not have comments explaining what functions actually do. To use Rust's docgen we want to add comments to code.

An example of a good comment is this:

```rust
// Adds two numbers together and returns the result
/// # Example
/// ```
/// // Value will be 300
/// let value = add_numbers(100, 200);
/// ```
fn add_numbers(a: i32, b: i32) -> i32 {
    a + b
}
```

Comments can contain markdown with examples, as seen above. We use the following standard for these comments:
https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text

(The same as the Rust STD library).

**Comment by L0uisJ0shua** [comment]
This is interesting! Can I take this up? @kanersps You can assign this to me!

**Comment by WouterPennings** [comment]
@L0uisJ0shua, I think Kane is offline at the moment, so I'll help you.
Yea, I have assigned you to the issue. Do you need help with anything or are you able to find you way around?

I would recommend you read this: [Development Guidelines](https://github.com/looplanguage/todo/issues/22). Not everything is of importance to you, but some points are (mainly conventions).

**Comment by kanersps** [comment]
> This is interesting! Can I take this up? @kanersps You can assign this to me!

Hey!

Thank you for your interest. I see that Wouter already assigned this to you, you're welcome to do this task :)

Let me know if there are any questions. There are quite a few things (like the handling of extension methods and suffix expressions) that are a bit scuffed. But most things should speak for itself.

Anyway, thanks!

**Comment by L0uisJ0shua** [comment]
> @L0uisJ0shua, I think Kane is offline at the moment, so I'll help you. Yea, I have assigned you to the issue. Do you need help with anything or are you able to find you way around?
> 
> I would recommend you read this: [Development Guidelines](https://github.com/looplanguage/todo/issues/22). Not everything is of importance to you, but some points are (mainly conventions).

Yes! I will check on the development guidelines before I get started on this.
